---
- name: Pull docker image
  docker_image:
    name: nginx
    tag: latest
  register: nginx_pull_rst
  
- name: Write Nginx configuration file
  template:
    src: conf.j2
    dest: /home/ubuntu/nginx.conf
  register: nginx_conf_rst

- name: Remove exisiting Nginx docker
  docker_container:
    name: nginx_ccc
    state: absent
  when: nginx_pull_rst.changed or nginx_conf_rst.changed

- name: Start the Nginx docker
  shell: >
    docker run
    -p 8080:8080
    -p 80:80
    -v /home/ubuntu/nginx.conf:/etc/nginx/conf.d/default.conf
    --name nginx_ccc
    -d nginx:latest
  when: nginx_pull_rst.changed or nginx_conf_rst.changed

- pause:
    seconds: 10
  when: nginx_pull_rst.changed or nginx_conf_rst.changed