---
- name: Pull docker image
  docker_image:
      name: nginx
      tag: latest

- name: Write Nginx configuration file
  template:
    src: conf.j2
    dest: /home/ubuntu/nginx.conf

- name: Check if the docker is running
  shell: "docker start nginx"
  ignore_errors: true
  no_log: true
  register: nginx_start

- name: Start the CouchDB docker
  shell: >
    docker run
    -v /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    --name nginx_ccc
    -d nginx:latest
  when: nginx_start.rc != 0 

- pause:
    seconds: 10