---
# Python
- name: Install Python2
  apt:
    name: python
    state: latest
    update_cache: yes

- name: Install pip
  become: yes
  apt:
    name: python-pip
    state: latest
    update_cache: yes

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Install Openstack
  pip:
    name: openstacksdk
    state: latest
