- name: Create security groups
  os_security_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    state: present
  loop: "{{ security_groups }}"

- name: Create a list of security groups so that they can be used when creating instances
  set_fact:
    os_basic_security_group: "{{ os_basic_security_group | default([]) + [ item.name ]}}"
  loop: "{{ security_groups }}"

- name: Create security group rules
  os_security_group_rule:
    security_group: "{{ item.name }}"
    protocol: "{{ item.protocol }}"
    port_range_min: "{{ item.port_range_min }}"
    port_range_max: "{{ item.port_range_max }}"
    remote_ip_prefix: "{{ item.remote_ip_prefix }}"
    state: present
  loop: "{{ security_groups }}"

- debug:
    msg: "Security groups {{ os_basic_security_group }} have been created"