---
avail_zone_comm: melbourne-qh2-uom
instance_image_comm: 955a0556-1224-4499-a895-87d54d5cbf32
instance_network_comm: qh2-uom-internal
instance_flavor_comm: uom.mse.2c9g

# security_group
security_groups:
    - name: automation-ssh
      description: "Security group for SSH"
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0
    - name: automation-http
      description: "Security group for HTTP"
      protocol: tcp
      port_range_min: 80
      port_range_max: 80
      remote_ip_prefix: 0.0.0.0/0


# volume
volume_size_comm: 62
volumes:
    - vol_name: alfa-vol
    - vol_name: bravo-vol
    - vol_name: charlie-vol
    - vol_name: delta-vol

# keypair
keypair_name_comm: id_nectar
keypair_public_key_file_comm: /home/ubuntu/.ssh/id_nectar.pub

# instances
instances:
    - name: alfa
    - name: bravo
    - name: charlie
    - name: delta