---
avail_zone_comm: melbourne-qh2-uom
instance_image_comm: afccf48a-9426-4618-86dc-0ceb636f0169
instance_network_comm: qh2-uom-internal
instance_flavor_comm: uom.mse.2c9g

# security_group
security_groups:
  name: os-ccc
  description: "auto: Security group for CCC"
  protocol: tcp
  remote_group: os-ccc
  remote_ip_prefix: 0.0.0.0/0
  rules:
    - port_range_min: 22
      port_range_max: 22
    - port_range_min: 80
      port_range_max: 80
    - port_range_min: 8080
      port_range_max: 8080

# volume
volumes:
  - vol_name: alfa-vol
    vol_size: 63
  - vol_name: bravo-vol
    vol_size: 63
  - vol_name: charlie-vol
    vol_size: 62
  - vol_name: delta-vol
    vol_size: 62

# keypair
keypair_name_comm: id_nectar
keypair_public_key_file_comm: /home/ubuntu/.ssh/id_nectar.pub

# instances
instances:
  - name: alfa
  - name: bravo
  - name: charlie
  - name: delta