---
- name: Test if Proxy setting already exist
  shell: grep "^http_proxy" /etc/environment
  register: test_proxy_exist

- name: Add Internet Proxy
  blockinfile:
    path: /etc/environment
    block: |
      http_proxy="http://wwwproxy.unimelb.edu.au:8000"
      https_proxy="http://wwwproxy.unimelb.edu.au:8000"
      ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"

- debug:
    msg: "/etc/environment: {{ lookup('file', '/etc/envrionment') }}"

- name: Restart SSH session
  meta: reset_connection