---
- name: Install docker-py
  pip:
    name: docker
    state: latest

- name: Login to private registry with write access
  docker_login:
    registry: "{{ docker_private_registry }}"
    username: "{{ docker_private_user }}"
    password: "{{ docker_private_passwd_write }}"


- name: Build and push all dockers
  docker_image:
    path: /home/ubuntu/CCC_Project_2/{{ item }}
    name: "{{ docker_private_registry }}/{{ docker_private_user }}/{{ item }}"
    tag: latest
    push: yes
  loop: "{{ docker_images_name }}"