---
- hosts: all
  vars_files:
    - host_vars/comm_config_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  pre_tasks:
    - name: Install Python2
      raw: sudo apt update; sudo apt -y install python

  roles:
    - config_comm
    - os_pre
  tasks:
    - name: Test connection to instance
      ping:
    # - os_server_facts:
    #     server: alfa
    # - debug:
    #     var: openstack_servers

