---
- hosts: all
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_db_all


- hosts: alfa
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_db_master