---
- hosts: localhost
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/docker_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - build_dockers

- hosts: all
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/docker_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - schedule_jobs

- hosts: alfa, bravo
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/docker_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - schedule_go_backend