---
- hosts: localhost
  vars_files:
    - host_vars/creation.yaml
  gather_facts: true

  roles:
    - role: os_pre
    - role: os_security_groups
    - role: os_volumes
    - role: os_keypair
    - role: os_instances
