---
- hosts: all
  vars_files:
    - host_vars/comm_config_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  pre_tasks:
    - name: Install Python2
      raw: sudo apt update; sudo apt -y install python

  roles:
    - config_comm
    - mount_volumes

- hosts: all
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_db_all


- hosts: alfa
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_db_master

- hosts: alfa, bravo
  vars_files:
    - host_vars/comm_config_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config_nginx

- hosts: localhost
  vars_files:
    - host_vars/db_config_vars.yaml
    - host_vars/docker_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - build_dockers

- hosts: all
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/docker_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - schedule_jobs

- hosts: alfa, bravo
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/docker_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - schedule_go_backend

- hosts: localhost
  vars_files:
    - host_vars/comm_config_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - build_frontend

- hosts: alfa, bravo
  vars_files:
    - host_vars/comm_config_vars.yaml
    - host_vars/db_config_vars.yaml
    - host_vars/docker_vars.yaml
    - host_vars/vault_vars.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - config_frontend
    - config_nginx
